#!/bin/bash

# Standard paranoia.  The `-e` is critical if we want failed tests to be
# reported on Travis.
set -euo pipefail

# Get an example program for testing if we don't have one yet.
if [ ! -d ./rust-buildpack-example-actix ]; then
    git clone https://github.com/emk/rust-buildpack-example-actix.git
fi

# Export the current UID so that our child processes can see it.  This will
# be used as a parameter in our `docker-compose-test.yml` file.
export UID GROUPS

# Run the build in a Heroku-like environment using `docker-compose`.
docker-compose -f docker-compose-test.yml up
